#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEBUG

const char NUMERIC_CHARS[] = "-0.123456789eE+";

#define B_INIT_SHEET_COUNT 1
#define B_INIT_COLUMN_COUNT 6
#define B_INIT_ROW_COUNT 1000

#define BUF_INIT_LINE_COUNT 1000
#define BUF_INIT_LINE_LEN 100

#endif  